curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Alabama/all_Alabama.zip > Alabama.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Alaska/all_Alaska.zip > Alaska.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Arizona/all_Arizona.zip > Arizona.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Arkansas/all_Arkansas.zip > Arkansas.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/California/all_California.zip > California.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Colorado/all_Colorado.zip > Colorado.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Connecticut/all_Connecticut.zip > Connecticut.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Delaware/all_Delaware.zip > Delaware.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/District_of_Columbia/all_District_of_Columbia.zip > District_of_Columbia.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Florida/all_Florida.zip > Florida.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Georgia/all_Georgia.zip > Georgia.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Hawaii/all_Hawaii.zip > Hawaii.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Idaho/all_Idaho.zip > Idaho.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Illinois/all_Illinois.zip > Illinois.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Indiana/all_Indiana.zip > Indiana.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Iowa/all_Iowa.zip > Iowa.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Kansas/all_Kansas.zip > Kansas.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Kentucky/all_Kentucky.zip > Kentucky.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Louisiana/all_Louisiana.zip > Louisiana.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Maine/all_Maine.zip > Maine.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Maryland/all_Maryland.zip > Maryland.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Massachusetts/all_Massachusetts.zip > Massachusetts.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Michigan/all_Michigan.zip > Michigan.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Minnesota/all_Minnesota.zip > Minnesota.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Mississippi/all_Mississippi.zip > Mississippi.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Missouri/all_Missouri.zip > Missouri.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Montana/all_Montana.zip > Montana.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Nebraska/all_Nebraska.zip > Nebraska.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Nevada/all_Nevada.zip > Nevada.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/New_Hampshire/all_New_Hampshire.zip > New_Hampshire.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/New_Jersey/all_New_Jersey.zip > New_Jersey.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/New_Mexico/all_New_Mexico.zip > New_Mexico.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/New_York/all_New_York.zip > New_York.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/North_Carolina/all_North_Carolina.zip > North_Carolina.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/North_Dakota/all_North_Dakota.zip > North_Dakota.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Ohio/all_Ohio.zip > Ohio.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Oklahoma/all_Oklahoma.zip > Oklahoma.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Oregon/all_Oregon.zip > Oregon.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Pennsylvania/all_Pennsylvania.zip > Pennsylvania.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Puerto_Rico/all_Puerto_Rico.zip > Puerto_Rico.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Rhode_Island/all_Rhode_Island.zip > Rhode_Island.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/South_Carolina/all_South_Carolina.zip > South_Carolina.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/South_Dakota/all_South_Dakota.zip > South_Dakota.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Tennessee/all_Tennessee.zip > Tennessee.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Texas/all_Texas.zip > Texas.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Utah/all_Utah.zip > Utah.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Vermont/all_Vermont.zip > Vermont.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Virginia/all_Virginia.zip > Virginia.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Washington/all_Washington.zip > Washington.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/West_Virginia/all_West_Virginia.zip > West_Virginia.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Wisconsin/all_Wisconsin.zip > Wisconsin.zip
curl http://www2.census.gov/ftp/census_2000/datasets/Summary_File_1_Supplement/Wyoming/all_Wyoming.zip > Wyoming.zip
